### ISSUE TITLE
✨ StarknetFetcher

### ISSUE THREAD

**Issue by EvolveArt** [astraly-labs/pragma-sdk#14]
### Feature Request

Current Behavior
--

Right now, there is no fetcher that can be used to retrieve the price of an on-chain asset only traded on Starknet.

**Expected Behavior**

There should be a new `fetcher` similar to `TheGraphFetcher`.
It should work with the following example asset:
```
{
        "type": "ONCHAIN",
        "source": "JEDISWAP",
        "key": "DEX",
        "detail": {
            "asset_name": "LORDS",
            "asset_address": "0x0124aeb495b947201f5fac96fd1138e326ad86195b98df6dec9009158a533b49",
            "metric": "price",
        },
        "decimals": 18,
}
```

Acceptance Criteria
--

An integration test suite should be added for this fetcher.
The contributor is free to use whatever indexing tool/API to query the underlying data.

**Supported Metrics**

`price` : When this metric is chosen, the fetcher should return a `SpotEntry` with the price given in USD terms
`liquidity`: USD denominated liquidity of the asset on the given source exchange.

Useful Resources
--

https://www.geckoterminal.com/dex-api
https://bitquery.io/products/dex
https://www.apibara.com/docs

**Comment by kasteph** [comment]
I can pick this up!

**Comment by EvolveArt** [comment]
> I can pick this up!

Assigned! Btw I've already added support for GeckoTerminal API, so this issue should probably use another source.

**Comment by kasteph** [comment]
@EvolveArt thanks! I was thinking of using `apibara`. Would that suit?

**Comment by EvolveArt** [comment]
> @EvolveArt thanks! I was thinking of using `apibara`. Would that suit?

Yes that would work :) Up to you to structure this as you like, as an external microservice or as an internal service
