### ISSUE TITLE
✨ Add default RPCs in the SDK

### ISSUE THREAD

**Issue by EvolveArt** [Astraly-Labs/pragma-sdk#16]
### Feature Request

Current Behavior
--
Right now, the SDK excepts an `RPC_KEY` environment variable in order to interact with testnet/mainnet.

Expected Behavior
--
The user shouldn't need to specify an `RPC_KEY` and the SDK should integrate a pre-defined sets of RPC endpoints that the SDK user can use.
The user should also be able to specify their own RPC endpoint.

**Comment by kasteph** [comment]
I can pick this up 😊

**Comment by EvolveArt** [comment]
> I can pick this up 😊

Assigned 🫡
